### ISSUE TITLE
Adapt app to Wazuh 4.1.3 and Splunk 8.1.2

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1022]
- [x] Migrate Wazuh API endpoints 
   - [x] [Registry key and registry values (Add registry values to registry key detail) ](https://github.com/wazuh/wazuh-splunk/issues/1026)
   - [x] [Migrate cluster/:node_id/files and manager/files  -> cluster/configuration | rules/files  | decoders/files | lists/files ](https://github.com/wazuh/wazuh-splunk/issues/1025)
- [x] [Check compatibility with Splunk 8.1.2 ](https://github.com/wazuh/wazuh-splunk/issues/1027)
