### ISSUE TITLE
Migrate cluster and manager files endpoints 

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1025]
Hi team.
We need to migrate this API endpoints `/manager/files` and `/cluster/{node_id}/files`  corresponding to this [#wazuh/7148](https://github.com/wazuh/wazuh/issues/7148)

- [x] Migrate configuration files endpoints to `/manager/configuration` and `/cluster/{node_id}/configuration` https://github.com/wazuh/wazuh/issues/7181)
  - [x] Read
  - [x] Edit
- [x] Migrate decoder files endpoints to `/decoders/files` https://github.com/wazuh/wazuh/issues/7179
  - [x] Read
  - [x] Edit
  - [x] Delete
  - [x] Upload/import
  - [x] Link to open the file in details
- [x] Migrate rule files endpoints to `/rules/files` https://github.com/wazuh/wazuh/issues/7178
  - [x] Read
  - [x] Edit
  - [x] Delete
  - [x] Upload/import
  - [x] Link to open the file in details
- [x] Migrate list files endpoints to `/lists/files`  https://github.com/wazuh/wazuh/issues/7180
  - [x] Read
  - [x] Edit
  - [x] Delete
  - [x] Upload/import
  - [x] Export list (keys/values)

**Comment by Desvelao** [comment]
### Update

Adapted the next actions to the API endpoints:

- manager configuration (`ossec.conf`)
  - Read
  - Edit
- Rule file
  - Read
  - Edit
  - Delete
- Decoder file
  - Read
  - Edit
  - Delete

**Comment by Desvelao** [comment]
### Update

- Fixed the import/uploading files functionality
- Fixed some links in rule/decoder details to open the related file
- Fixed some HTML elements that didn't show related to deprecated fields API response object
