### ISSUE TITLE
Testing Wazuh 4.2.0 revision 4202

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1079]
We need to perform testing of the changes introduced in the code revision 4202 in production mode.
Also, we need to perform a regression test with these changes over our general checks.

Checks for 4202:

- [x] Cannot pin search filters on Edge - Chip style collapses [#1070](https://github.com/wazuh/wazuh-splunk/pull/1070)
- [x] Tables without server side pagination [#1074](https://github.com/wazuh/wazuh-splunk/pull/1074)
- [x] Added cache control [#1078](https://github.com/wazuh/wazuh-splunk/pull/1078)
- [x] Fixed gear icon in fim table [#1077](https://github.com/wazuh/wazuh-splunk/pull/1077)

General checks:

- [x] Firefox - Splunk 8.1.2
- [x] Chrome - Splunk 8.1.2
- [ ] Safari - Splunk 8.1.2

**Comment by pablomarga** [comment]
Visualizations of `Virustotal` of an agent are not working but the alerts are shown in discover. i have added this alert manually to the alert.json. Visualizations of manager are working fine.
![Screenshot_20210507_131012](https://user-images.githubusercontent.com/46006326/117441428-a3226580-af35-11eb-8259-26f79188cf6f.png)
![Screenshot_20210507_130958](https://user-images.githubusercontent.com/46006326/117441432-a3bafc00-af35-11eb-829b-baba1ac12529.png)
