### ISSUE TITLE
Security issues with Splunk Cloud

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1086]
**Description** 
We got this feedback from a user related to the compatibility with Splunk Cloud

```
The Cloud operations and security teams have determined that the Wazuh App is not compatible and/or secure within the Splunk Cloud service architecture. Please see their comments below:

#Custom 4.1.3 - SplunkAppForWazuh
Review fails vetting and cannot be installed.

The app did not meet security and functionality requirements for Splunk Cloud for the following reasons:
[The application can be configured for unencrypted communication, which is not permitted in Splunk Cloud. All communication must be encrypted (HTTPS preferred).]

Only files under the bin, lib, appserver/controllers directories may have executable permissions. File: appserver/static/js/libs/codemirror-conv/javascript.js
tmpUrl (endpoint) is not verified to have a 'https' schema. Only URLs with a 'https' schema may be requested from a Splunk cloud environment. File: appserver/static/js/services/requestService/requestService.js Line Number: 47,50,53,56

The default/inputs.conf specifies splunktcp, which is prohibited in Splunk Cloud. An alternative is to use splunktcp-ssl. Stanza: [splunktcp://9997]. File: default/inputs.conf Line Number: 1
Once these issues are remedied you can resubmit your app for review.
```

We need to solve these security issues  to make compatible our App

**Tasks**
- [ ] Check permissions for `appserver/static/js/libs/codemirror-conv/javascript.js`
- [x] Resolve https for endpoints at `appserver/static/js/services/requestService/requestService.js`
- [x] Check refactor for `splunktcp` in `default/inputs.conf`

**Comment by Desvelao** [comment]
### How to validate the app quality:
I found a Splunk utility app to check the app quality
https://dev.splunk.com/enterprise/docs/developapps/testvalidate/appinspect/useappinspectclitool/

### Tasks
- [ ] Check permissions for `appserver/static/js/libs/codemirror-conv/javascript.js`

I unzipped the app package and checked the permission for the file. It has not execution permission.
![image](https://user-images.githubusercontent.com/34042064/121337686-16483e80-c91d-11eb-8c68-6e72c2878e6c.png)

I am researching and I found using the `file` command, returns the file is executable and is a "Python script" (maybe due a its content):
![image](https://user-images.githubusercontent.com/34042064/121337836-3bd54800-c91d-11eb-9bdf-4ba17cde19f9.png)

- [ ] Resolve https for endpoints at `appserver/static/js/services/requestService/requestService.js`
I review the code and I am not sure which is the problem or how to solve.

```js
/**
     * Generated and returns the browser base URL + Splunk Port
     */
    const getBaseUrl = () => {
      return `${window.location.href.split(/\/[a-z][a-z]-[A-Z][A-Z]\//)[0]}/`
    }

    /**
     * Generates and returns the browser base URL + Splunk Port
     */
    const getWellFormedUri = endpoint => {
      try {
        return `${getBaseUrl()}en-US/custom/SplunkAppForWazuh/${endpoint}`
      } catch (err) {
        return Promise.reject(err)
      }
    }

    /**
     * Performs a HTTP request
     * @param {String} method
     * @param {String} endpoint
     * @param {Boolean} includedApi
     * @param {Object} payload
     */
    const httpReq = async (method, endpoint, payload = {}) => {
      try {
        if (!method || !endpoint) {
          throw new Error('Missing parameters')
        }
        const tmpUrl = getWellFormedUri(endpoint)
        const data = {}

        // Set content type to form urlencoded
        $http.defaults.headers.post['Content-Type'] =
          'application/x-www-form-urlencoded'
        // GET METHOD
        if (method === 'GET')
          Object.assign(data, await $http.get(tmpUrl, { params: payload }))
       ....   
       
```

- [ ] Check refactor for `splunktcp` in `default/inputs.conf` 
The error disappears when using `splunktcp-ssl` instead of `splunktcp` in `default/inputs.conf`. I am not sure about the implications of change.

**Comment by frankeros** [comment]
> I unzipped the app package and checked the permission for the file. It has not execution permission.
> ![image](https://user-images.githubusercontent.com/34042064/121337686-16483e80-c91d-11eb-8c68-6e72c2878e6c.png)
> 
> I am researching and I found using the `file` command, returns the file is executable and is a "Python script" (maybe due to its content):
> ![image](https://user-images.githubusercontent.com/34042064/121337836-3bd54800-c91d-11eb-9bdf-4ba17cde19f9.png)
> 
> I am not sure, how it could be solved.

I think this happens to because the gzip is not keeping the original permissions of the files. Then when the files are unzipped they take the default permissions of the OS.
A possible solution is adding the flag `-p` for the `tar` command to preserve the permissions during the build.

**Comment by frankeros** [comment]
>     * Check permissions for `appserver/static/js/libs/codemirror-conv/javascript.js`

This was de answer from Splunk 
>@Franco Charriol   You might look at how the app is being zipped up and submitted.   For example if you're using a windows app to create the tar.gz, it'll have execute permissions on static files.   Workaround is to actually tar it on a linux FS.
