### ISSUE TITLE
Take `sourcetype` filter for internal queries from inputs.conf

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1101]
| Version | Source branch
| --- | --- |
| 4.1.5 | 4.1-8.1 | 

### Description:
Some users use different `sourcetype` values in their forwarders. Currently, we are assuming that the value for this filter is always `wazuh`, so we need to make it configurable.
The `sourcetype` is defined in the forwarder and this setting is configured from our installation guide:
```bash
curl -so /opt/splunkforwarder/etc/system/local/inputs.conf https://raw.githubusercontent.com/wazuh/wazuh-splunk/v4.2.0-8.1.3/setup/forwarder/inputs.con
```
We need to let the user choose what `sourcetype` want to use in the same way that the index. 

#### Tasks: 

- [x] Add a new selector with the possible values for `sourcetype`
- [x] Replace all internal queries changing dynamically the value of this filter from the selected value
- [ ] Update documentation about this step: 
   - [ ] Update screenshot of API page
   - [ ] Add step 5 with the next content:
     - This should mention the selection of the index and the source type
     - The default values are  for index `wazuh` and for source type `*`
     - In a note "The Wazuh app considers as valid index all indexes that contain the word "wazuh" in the source type, the default value for source type is 'wazuh'. " 

#### Acceptance Criteria

- The default selected value should be `*`, to get from any `sourcetype`
- The other values should be taken dynamically from the configured `sourcetype` like the index
- The fix should be cherry pricked to 4.2.0 and 4.2.1

**Comment by frankeros** [comment]
Update: 
![image](https://user-images.githubusercontent.com/26828184/131672505-441ea626-c355-4710-a4a6-a16f68465a2b.png)

We need to improve the way as the selected API, Index, and Source Type is displayed

**Comment by matiasmoreno876** [comment]
> Update

This is the [PR](https://github.com/wazuh/wazuh-documentation/pull/4219) with the update of the official documentation.

> Images

![image](https://user-images.githubusercontent.com/49887871/131674379-08c7d474-afd6-4391-be10-9c0e10d7b4c8.png)
![image](https://user-images.githubusercontent.com/49887871/131674435-081f8d23-ec78-4258-941f-6eae12e2ea28.png)

**Comment by matiasmoreno876** [comment]
> Updated: 

![image](https://user-images.githubusercontent.com/49887871/131684706-da3989b7-f6ec-41a7-870e-d1f2d6380969.png)
![image](https://user-images.githubusercontent.com/49887871/131684759-cb54a5b5-03e1-40cb-825c-a5c915812b51.png)

**Comment by frankeros** [comment]
Update 
- Improve the way that the selected API, index, and source type is displayed
- Add quick settings to change the related values easily 

![image](https://user-images.githubusercontent.com/26828184/131722609-e2506b08-803e-46b5-b803-7db556adddf1.png)

![image](https://user-images.githubusercontent.com/26828184/131722548-069628c4-3802-4a0c-9441-3e5f7fc2b5cd.png)

**Comment by matiasmoreno876** [comment]
> Updated:

Added new steps for quick configurations in the Wazuh documentation.

![image](https://user-images.githubusercontent.com/49887871/131740057-ed178afb-4ca6-41c2-bedf-e04e04fbacf9.png)

**Comment by frankeros** [comment]
Improvement of error logging when checking/adding an API is requested:
Now the complete error is logged in `/opt/splunk/var/log/splunk/SplunkAppForWazuh.log`
![image](https://user-images.githubusercontent.com/26828184/132853978-8aae82d3-70c0-403b-9632-fe915c44a2f2.png)
