### ISSUE TITLE
Create dictionary for permissions

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-splunk#1159]
**Describe the solution you'd like**
We should create a dictionary that allows us to define all the permissions that may be required in the app in a central location. It should also allow for parameters to be passed in order to generate specific permissions dinamically.

**Additional context**
A description for all the actions, resources and endpoints can be found here https://documentation.wazuh.com/current/user-manual/api/rbac/reference.html

**Tasks**

- [x] Method for accesing resources
- [x] Method for accesing actions
- [x] Method relating actions to resources
- [ ] Method generating requirements for each endpoint
