### ISSUE TITLE
Implement access control on app's views based on RBAC

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1164]
# Implement access control on app's views based on RBAC

## Description

In order to implement RBAC we need to define the resources, actions and polices required on each view of the app.
Then, create a requirement object using the new `requirementService` to later on validate the access using the new `validationService`.
Depending on the result of the validation service, the view will allow or deny such actions over such resources (f.e: update rules, in this case, the button to edit the rules should be disabled)

## Possible **actions** and app analysis

- [x] Active response
- [x] Agents
- [x] Ciscat
- [x] Cluster
- [x] Decoders
- [x] Group
- [x] Lists
- [x] Logtest
- [x] Manager
- [x] Mitre
- [x] Rootcheck
- [x] Rules
- [x] SCA
- [x] Security
- [x] Syscheck
- [x] Syscollector
- [x] Task
- [x] Vulnerability

### Active Response

| Action                  | App section | Comments |
| ----------------------- | ----------- | -------- |
| active-response:command | -           | -        |

### Agents

Each action can be applied to (agent:id, agent:group).

| Action             | App section                     | Comments                                                                              |
| ------------------ | ------------------------------- | ------------------------------------------------------------------------------------- |
| agent:create       | -                               | -                                                                                     |
| agent:delete       | -                               | -                                                                                     |
| agent:modify_group |                                 |                                                                                       |
|                    | Agent                           | ![alt text][logo]                                                                     |
|                    | Management > Groups             | Add or remove agents from group (PUT, DELETE)                                         |
| agent:read         |                                 |                                                                                       |
|                    | Overview                        | Agents summary (total, active, disconnected, never connected                          |
|                    |                                 |                                                                                       |
|                    | Overview > Security Events      | `Top 5 agents` <br/> `Agents Status`                                                  |
|                    | Overview > Integrity monitoring | `Top 5 agents`                                                                        |
|                    |                                 |                                                                                       |
|                    | Overview > Policy monitoring    | `Top 5 agents` <br/> `Alerts Summary`                                                 |
|                    | Overview > System auditing      | `Agents`                                                                              |
|                    | Overview > OpenSCAP             | `Top 5 agents`                                                                        |
|                    |                                 |                                                                                       |
|                    | Overview > Vulnerabilities      | `Most affected agents`                                                                |
|                    | Overview > VirusTotal           | `Top 10 agents with positive scans`                                                   |
|                    | Overview > MITRE ATT&CK         | `Top tactics by agent` <br/> `MITRE techniques by agent`                              |
|                    |                                 |                                                                                       |
|                    | Overview > PCI DSS              | `Top 10 agents by alerts number` <br/> `Requirements by agent` <br/> `Alerts summary` |
|                    | Overview > GPDR                 | `Top 10 agents by alerts number` <br/> `Requirements by agent` <br/> `Alerts summary` |
|                    | Overview > HIPAA                | `Alerts volume by agent` <br/> `Most active agents` <br/> `Alerts summary`            |
|                    | Overview > NIST                 | `Top 10 agents by alerts number` <br/> `Most active agents` <br/> `Alerts summary`    |
|                    |                                 |                                                                                       |
|                    | Agents                          | -                                                                                     |
|                    | Agent                           | -                                                                                     |
|                    |                                 |                                                                                       |
|                    | Management > Groups             | -                                                                                     |
|                    | Management > Status             | `Last registered agent` <br/> `Agents summary`                                        |
|                    | Management > Cluster            | `Information` shows the total number of agents                                        |
|                    |                                 |                                                                                       |
|                    | Discover                        | `agent.*` filter                                                                      |
| agent:restart      |                                 |                                                                                       |
|                    | Agent                           | there is a restart button at the top right corner                                     |
| agent:upgrade      | -                               | -                                                                                     |

[logo]: https://user-images.githubusercontent.com/15186973/138260068-ca779271-6213-4b3a-aeb3-000f579961e0.png

### CIS-CAT

Each action can be applied to (agent:id, agent:group).

| Action      | App section        | Comments |
| ----------- | ------------------ | -------- |
| ciscat:read |                    |          |
|             | Overview > CIS-CAT | -        |
|             | Agent > CIS-CAT    | -        |

### Cluster

Each action can be applied to (node:id).

| Action                  | App section                                     | Comments                         |
| ----------------------- | ----------------------------------------------- | -------------------------------- |
| cluster:read_api_config | -                                               | -                                |
| cluster:read            |                                                 |                                  |
|                         | Management > Configuration                      | `GET /cluster/nodes`             |
|                         | Management > Status                             | `GET /cluster/{node}/status`     |
|                         | Management > Cluster                            | Resolver: `management-states.js` |
| cluster:restart         |                                                 |                                  |
|                         | Management > Configuration > Edit Configuration | -                                |
|                         | Management > Status                             | -                                |
| cluster:status          |                                                 |                                  |
|                         | Management > Configuration > Edit Configuration | `GET /cluster/status`            |
|                         | Management > Status                             | `GET /cluster/status`            |
|                         | Management > Logs                               | `GET /cluster/status`            |
|                         | Management > Cluster                            | `GET /cluster/status`            |
|                         | Agents                                          | `GET /cluster/status`            |
| cluster:update_config   |                                                 |                                  |
|                         | Management > Configuration > Edit Configuration | -                                |

### Decoders

Each action can be applied to (decoder:file).

| Action          | App section           | Comments |
| --------------- | --------------------- | -------- |
| decoders:read   |                       |          |
|                 | Management > Decoders | -        |
|                 | Management > Status   | -        |
| decoders:update | -                     |          |
|                 | Management > Decoders | -        |
| decoders:delete |                       |          |
|                 | Management > Decoders | -        |

### Groups

Each action can be applied to (group:id).

| Action                   | App section                                    | Comments                               |
| ------------------------ | ---------------------------------------------- | -------------------------------------- |
| group:create             |                                                |                                        |
|                          | Management > Groups                            | `POST /groups`                         |
| group:delete             |                                                |                                        |
|                          | Management > Groups > Delete Group             | `DELETE /groups/{group:id}`            |
| group:modify_assignments |                                                |                                        |
|                          | Management > Groups                            | Add or remove Agents from a group      |
|                          | Agent                                          | ![alt text][logo]                      |
| group:read               |                                                |                                        |
|                          | Agent                                          | `GET /groups`                          |
|                          | Management > Groups                            | `GET /groups`                          |
| group:update_config      |                                                |                                        |
|                          | Management > Groups > Edit Group Configuration | `PUT /groups/{group:id}/configuration` |

### Lists

Each action can be applied to (list:file).

| Action      | App section        | Comments |
| ----------- | ------------------ | -------- |
| list:read   |                    |          |
|             | Management > Lists | -        |
| list:update | -                  | -        |
|             | Management > Lists | -        |
| list:delete | -                  | -        |
|             | Management > Lists | -        |

### Logtest

Resourceless.

| Action      | App section | Comments |
| ----------- | ----------- | -------- |
| logtest:run | -           | -        |

### Manager

Resourceless.

| Action                  | App section                                     | Comments |
| ----------------------- | ----------------------------------------------- | -------- |
| manager:read_api_config | -                                               | -        |
| manager:read            |                                                 |          |
|                         | Management > Configuration > Edit Configuration | -        |
|                         | Management > Status                             | -        |
|                         | Management > Logs                               | -        |
| manager:restart         | -                                               | -        |
|                         | Management > Configuration > Edit Configuration | -        |
|                         | Management > Status                             | -        |
| manager:update_config   | -                                               | -        |
|                         | Management > Configuration > Edit Configuration | -        |

### MITRE

Resourceless.

| Action     | App section                    | Comments                         |
| ---------- | ------------------------------ | -------------------------------- |
| mitre:read |                                |                                  |
|            | Overview > MITRE > Show Alerts | Resolver `GET /mitre`            |
|            | Overview > MITRE > Show Alerts | Click on techniques `GET /mitre` |

### Rootcheck

Each action can be applied to (agent:id, agent:group).

| Action          | App section             | Comments                         |
| --------------- | ----------------------- | -------------------------------- |
| rootcheck:clear | -                       | -                                |
| rootcheck:read  |                         |                                  |
|                 | Agent                   | `GET /rootcheck/{id}/last_scan ` |
|                 | Agent > Security Events | `GET /rootcheck/{id}/last_scan`  |
| rootcheck:run   | -                       | -                                |

### Rules

Each action can be applied to (rule:file).

| Action       | App section         | Comments |
| ------------ | ------------------- | -------- |
| rules:read   |                     |          |
|              | Management > Rules  | -        |
|              | Management > Status | -        |
| rules:update | -                   |          |
|              | Management > Rules  | -        |
| rules:delete |                     |          |
|              | Management > Rules  | -        |

### SCA

Each action can be applied to (agent:id, agent:group).

| Action   | App section | Comments        |
| -------- | ----------- | --------------- |
| sca:read |             |                 |
|          | Agent > SCA | `GET /sca/{id}` |

### Security - DONE

| Action                 | App section | Comments |
| ---------------------- | ----------- | -------- |
| security:create_user   | -           | -        |
| security:create        | -           | -        |
| security:delete        | -           | -        |
| security:edit_run_as   | -           | -        |
| security:read_config   | -           | -        |
| security:read          | -           | -        |
| security:revoke        | -           | -        |
| security:update_config | -           | -        |
| security:update        | -           | -        |

### Syscheck

Each action can be applied to (agent:id, agent:group).

| Action         | App section                  | Comments                       |
| -------------- | ---------------------------- | ------------------------------ |
| syscheck:clear | -                            | -                              |
| syscheck:read  |                              |                                |
|                | Agent                        | `GET /syscheck/{id}/last_scan` |
|                | Agent > Security Events      | `GET /syscheck/{id}/last_scan` |
|                | Agent > Integrity Monitoring | `GET /syscheck/{id}`           |
|                | Agent > Inventory Data       | reportingService               |
| syscheck:run   | -                            | -                              |

### Syscollector

Each action can be applied to (agent:id, agent:group).

| Action            | App section             | Comments                                                                           |
| ----------------- | ----------------------- | ---------------------------------------------------------------------------------- |
| syscollector:read |                         |                                                                                    |
| -                 | Agent > Security Events | Resolver <br/> `GET /syscollector/{id}/hardware` <br/> `GET /syscollector/{id}/os` |
| -                 | Agent > Inventory Data  | Resolver & reportingService                                                        |

### Task

Resourceless.

| Action       | App section | Comments |
| ------------ | ----------- | -------- |
| tasks:status | -           | -        |

### Vulnerability

Each action can be applied to (agent:id, agent:group).

| Action             | App section                         | Comments |
| ------------------ | ----------------------------------- | -------- |
| vulnerability:read |                                     |          |
|                    | Overview > Vulnerabilities          | -        |
|                    | Agent > Vulnerabilities             | -        |
|                    | Agent > Vulnerabilities > Inventory | -        |

**Comment by AlexRuiz7** [comment]
Having the securiryService implemented, each route resolver must add the following chunk of code

```js
  requirementsList: [
    '$security_service',
    ($security_service) => {
      $security_service.getRequirementsOfController(<controllerName>)
    }
  ]
```

**Comment by AlexRuiz7** [comment]
## Missing controllers on the actions map

- [ ] ag-cve
- [ ] ag-pm
- [ ] ag-osquery
- [ ] ag-virustotal
- [ ] ag-docker
- [ ] ag-audit
- [ ] ag-os
- [ ] ag-pci
- [ ] ag-gdpr
- [ ] ag-hipaa
- [ ] ag-nist

**Comment by AlexRuiz7** [comment]
Note:
`requirementService` breaks on the configuration editor
![image](https://user-images.githubusercontent.com/15186973/140404701-29f06f5d-e5f3-40bc-bab9-80f828f02089.png)

**Comment by yenienserrano** [comment]
code to create the 7 users in wazuh to test RBAC
```
async createUser(){


      const usersArray = [
        {id: 1, username: 'Administrator1.', password: 'Administrator1.', role:'administrator', usernameSplunk: 'administrator1.'},
        {id: 2, username: 'Readonly1.', password: 'Readonly1.', role:'readonly', usernameSplunk: 'readonly1.'},
        {id: 3, username: 'Users_admin1.', password: 'Users_admin1.', role:'users_admin', usernameSplunk: 'users_admin1.'},
        {id: 4, username: 'Agents_readonly1.', password: 'Agents_readonly1.', role:'agents_readonly', usernameSplunk: 'agents_readonly1.'},
        {id: 5, username: 'Agents_admin1.', password: 'Agents_admin1.', role:'agents_admin', usernameSplunk: 'agents_admin1.'},
        {id: 6, username: 'Cluster_readonly1.', password: 'Cluster_readonly1.', role:'cluster_readonly', usernameSplunk: 'cluster_readonly1.'},
        {id: 7, username: 'Cluster_admin1.', password: 'Cluster_admin1.', role:'cluster_admin', usernameSplunk: 'cluster_admin1.'}
      ]

      for(let i = 0; i < usersArray.length; i++){
        const users = await this.apiReq('/security/users',
        {
          content: JSON.stringify({username:usersArray[i].username, password: usersArray[i].password}),
          origin: "json"
        },
       'POST')


        if(users.data.data.affected_items.length < 1){
          console.log(`Ya hay un usuario creado con ${usersArray[i].username}`)
          break
        }

        let idUser = users.data.data.affected_items[0].id
  
        await this.apiReq(`/security/users/${idUser}/roles?role_ids=${usersArray[i].id}`,
        {},
       'POST')

      }

      const listUsers = await this.apiReq('/security/users')

      console.log(listUsers)

      return listUsers
    }

```

**Comment by Desvelao** [comment]
### Changes
branch: `rbac/implement-access-control-on-views`

- Created a factory to store the user permissions
- Added a resolver in some states to update the user permissions. This is required due to the token management is located in the backed. We should remove these resolvers if we move the token management to the frontend
- Changes in the `security_service` service:
  - Created a method to update the user permissions in the factory (used in the state resolvers)
  - Created 2 methods to check if the user has permissions (one check if the user has permissions for agents by id or group)
- Adapt the views and controllers to manage RBAC permissions
- Added one button to add a new file in `Management > Ruleset > Rules` and `Management > Ruleset > Decoders`
- Fixed some minor bugs:
    - `Management > Groups`: Request to remove agent of group
    - `Management > Ruleset > Rules/Decoders > Rule/Decoder detail (editable files): Save the edited file
    - Other minor bugs
    
### Driagram
![image](https://user-images.githubusercontent.com/34042064/142440367-579d6bdf-9dbc-4843-a083-02da8567256b.png)

### `$security_service`
Added methods:
- `userHasPermissions`: check if the user has the required permissions compared to the permissions stored in the `userPermissions` factory
```ts
userHasPermissions(requiredPermissions: {[securityAction: SecurityAction]: SecurityResource[]}): boolean
```
- `userHasPermissionsSecurityActionWithAgent`: check if the user has the required permissions related to agents using the agent data to use the `id` and `group`
```ts
userHasPermissionsSecurityActionWithAgent(requiredSecurityAction: {[securityAction: SecurityAction]: SecurityResource[]}, agentData: {id: string, group: string[]}): boolean
```
- `updateUserPermissions`: do a request to `GET /security/user/me/policies` and store the result in to the `userPermissions` factory
```ts
updateUserPermissions(): void
```

**Comment by AlexRuiz7** [comment]
https://github.com/wazuh/wazuh-splunk/compare/27766a565d05...5e821ac65d9b

**Comment by AlexRuiz7** [comment]
## Testing

In order to test that the RBAC is working as expected, we must verify the app's behaviour by using different user policies/roles.

**Default roles**
- [ ] administrator
Full access.
- [ ] agents_admin
Full access to all agents related functionalities.
- [ ] agents_readonly
Read only role for agents related functionalities.
- [ ] cluster_admin
Full access to all manager related functionalities.
- [ ] cluster_readonly
Read only role for manager related functionalities.
- [ ] readonly
Read all the information of the system.
- [ ] users_admin
Full access to all users related functionalities.

**Comment by AlexRuiz7** [comment]
## Errors

- Manager tab
```js
TypeError: Cannot read properties of undefined (reading 'destroy')
```
https://github.com/wazuh/wazuh-splunk/blob/5e821ac65d9be87b609f978dd7d15901da75c653/SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js#L194

- Agents tab
```js
Error: Already have instance with id: searchTopAgent
```

![rbac_error_01](https://user-images.githubusercontent.com/15186973/146049724-57b2b50b-e2a6-4dd8-a11b-adc8369d83a0.gif)

**Comment by AlexRuiz7** [comment]
## agents_admin

- [ ] The security tab on the top navigation bar should not be displayed due to lack of permissions.
- [ ] These sections in the Agent's overview should not be visible and are causing errors when accesed
![image](https://user-images.githubusercontent.com/15186973/146763690-a67dc911-773f-4abe-a8d2-45fdfe162df2.png)

**Comment by AlexRuiz7** [comment]
![rbac](https://user-images.githubusercontent.com/15186973/147565979-daecb881-6314-40f6-8a0a-9449c8a6f6ea.gif)

**Comment by AlexRuiz7** [comment]
## Controlleres to update
- [ ] appserver/static/js/controllers/agents/agents/agentsCtrl.js
- [ ] appserver/static/js/controllers/agents/audit/agentsAuditCtrl.js
- [ ] appserver/static/js/controllers/agents/ciscat/agentsCiscatCtrl.js
- [ ] appserver/static/js/controllers/agents/configuration-assessment/agentsConfigurationAssessmentsCtrl.js
- [ ] appserver/static/js/controllers/agents/cve/agentsCveCtrl.js
- [ ] appserver/static/js/controllers/agents/docker/agentsDockerCtrl.js
- [ ] appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
- [ ] appserver/static/js/controllers/agents/gdpr/agentsGdprCtrl.js
- [ ] appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
- [ ] appserver/static/js/controllers/agents/hipaa/agentsHipaaCtrl.js
- [ ] appserver/static/js/controllers/agents/inventory/inventoryCtrl.js
- [ ] appserver/static/js/controllers/agents/nist/agentsNistCtrl.js
- [ ] appserver/static/js/controllers/agents/osquery/osqueryCtrl.js
- [ ] appserver/static/js/controllers/agents/pcidss/agentsPciCtrl.js
- [ ] appserver/static/js/controllers/agents/policy-monitoring/agentsPolicyMonitoringCtrl.js
- [ ] appserver/static/js/controllers/agents/scap/agentsOpenScapCtrl.js
- [ ] appserver/static/js/controllers/agents/virustotal/agentsVirusTotalCtrl.js
- [ ] appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
- [ ] appserver/static/js/controllers/management/cdb/managerCdbCtrl.js
- [ ] appserver/static/js/controllers/management/cdb/managerCdbIdCtrl.js
- [ ] appserver/static/js/controllers/management/configuration/configurationCtrl.js
- [ ] appserver/static/js/controllers/management/decoders/managerDecodersCtrl.js
- [ ] appserver/static/js/controllers/management/decoders/managerDecodersIdCtrl.js
- [ ] appserver/static/js/controllers/management/groups/groupsCtrl.js
- [ ] appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
- [ ] appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
- [ ] appserver/static/js/controllers/management/status/statusCtrl.js

**Comment by AlexRuiz7** [comment]
### Bugs

- [ ] Security < Role Mapping: "No Authorization Token provided" as a reponse when a new Role-Mapping is created. The table refuses to show the new data. It also fails when sometimes when a role mapping is removed.
- [ ] Using "wazuh" as the API user is not working (reponse data differs from wazuh-wui)

Using "wazuh"
![image](https://user-images.githubusercontent.com/15186973/147588086-1c3df19b-3f7a-4c92-b03a-c7cdac01a5e6.png)

Using "wazuh-wui"
![image](https://user-images.githubusercontent.com/15186973/147588166-cac1d9b8-987d-4644-a4d4-7b582b98b18d.png)

- [ ] Management < Groups: new group's checksum is missing on the table when a new group is created

**Comment by AlexRuiz7** [comment]
![image](https://user-images.githubusercontent.com/15186973/147594965-3f55fe03-e8bd-49d9-9648-9a5e869bf2e0.png)

**Comment by AlexRuiz7** [comment]
## Blocker encountered

The App performs some checks that neede to know some information about the cluster status (whether daemons are ready) in order to work. To do so, the App launches some queries to the `/cluster/status` endpoint, and some users might have permissions to request such information (as the `agents_readonly` role). This results on the application entering on an stalemate state, as any further request or navigation is blocked due to these checks failing.

Here are the logs the represent this situation, using a user with the `agents_readonly` has its only role.

```python
ERROR: 2022/01/04 16:04:37: 'Wazuh_API::catch_exceptions() GET /cluster/status request failed with status 403
{
    "title": "Permission Denied",
    "detail": "Permission denied: Resource type: *:*",
    "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.2/user-manual/api/rbac/configuration.html",
    "dapi_errors": {
        "unknown-node": {
            "error": "Permission denied: Resource type: *:*"
        }
    },
    "error": 4000
}'
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 111, in catch_exceptions
    + json.dumps(response.json(), indent=4)
Exception: GET /cluster/status request failed with status 403
{
    "title": "Permission Denied",
    "detail": "Permission denied: Resource type: *:*",
    "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.2/user-manual/api/rbac/configuration.html",
    "dapi_errors": {
        "unknown-node": {
            "error": "Permission denied: Resource type: *:*"
        }
    },
    "error": 4000
}

ERROR: 2022/01/04 16:04:37: 'Error checking API connection: GET /cluster/status request failed with status 403
{
    "title": "Permission Denied",
    "detail": "Permission denied: Resource type: *:*",
    "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.2/user-manual/api/rbac/configuration.html",
    "dapi_errors": {
        "unknown-node": {
            "error": "Permission denied: Resource type: *:*"
        }
    },
    "error": 4000
}'
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/appserver/controllers/manager.py", line 527, in check_connection_by_id
    output = self.get_cluster_info(api)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/appserver/controllers/manager.py", line 648, in get_cluster_info
    current_api=api
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 297, in make_request
    raise e
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 178, in make_request
    response = catch_exceptions(response)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 119, in catch_exceptions
    raise e
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 111, in catch_exceptions
    + json.dumps(response.json(), indent=4)
Exception: GET /cluster/status request failed with status 403
{
    "title": "Permission Denied",
    "detail": "Permission denied: Resource type: *:*",
    "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.2/user-manual/api/rbac/configuration.html",
    "dapi_errors": {
        "unknown-node": {
            "error": "Permission denied: Resource type: *:*"
        }
    },
    "error": 4000
}'
```

After discussing this situation with the rest of the development team, we have decided that these requests are not caused by the user's activity, but by the architecture and the design of the App (for some reason these checks are a barebone of the App), so these request will be launched against the API using a private token (for the wazuh user), and will no longer use the user's token. This won't by any means allow a user to access unallowed information, as the App's views are dynamically generated based on the user's permissions.

Every request to be launched as a result of user's activity will still use the user's token, with its respective permissions.

**Comment by AlexRuiz7** [comment]
## Role `agents_readonly`
Entering the `Agents > Inventory Data` throws the following errors:

```python
ERROR: 2022/01/11 15:36:06: 'Wazuh_API::catch_exceptions() GET /syscollector/001/hardware request failed with status 403
{
    "title": "Permission Denied",
    "detail": "Permission denied: Resource type: agent:id",
    "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.2/user-manual/api/rbac/configuration.html",
    "dapi_errors": {
        "unknown-node": {
            "error": "Permission denied: Resource type: agent:id"
        }
    },
    "error": 4000
}'
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/wazuh_api.py", line 107, in catch_exceptions
    + json.dumps(response.json(), indent=4)
Exception: GET /syscollector/001/hardware request failed with status 403
{
    "title": "Permission Denied",
    "detail": "Permission denied: Resource type: agent:id",
    "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.2/user-manual/api/rbac/configuration.html",
    "dapi_errors": {
        "unknown-node": {
            "error": "Permission denied: Resource type: agent:id"
        }
    },
    "error": 4000
}
```

```js
Uncaught (in promise) Error: Cannot read properties of undefined (reading '0')
    at Inventory.init (inventoryCtrl.js:152:15)
    at Inventory.$onInit (inventoryCtrl.js:105:14)
    at ei (router.js:16:108113)
    at Object.<anonymous> (router.js:16:102666)
    at angular.js:22:134
    at ra (angular.js:90:380)
    at p (angular.js:75:342)
    at g (angular.js:67:426)
    at angular.js:67:51
    at angular.js:72:198
```

**Comment by AlexRuiz7** [comment]
- A problem where the App stopped working after upgrading an old environment to use RBAC has been fixed. This was caused by the old API registries already on the database not having the new `runAs` property.
- The error message being shown for the error before was not that great, so it has been improved.

**Comment by AlexRuiz7** [comment]
* A problem where the Dropwdown stopped working has been fixed by reverting the commit b3460535e7992639f2eafebaf4d46944b64a7d87. 
The problem was caused due to the use of the ng-if directive and the Dopwdown component. The Dropdown component is initialized on the controller with a DOM's element ID that does not exist at that time. Only the ng-if directives that do not share the same JS controler with a Dropdown componnet has been kept.
The JS controllers to review are (those that can't be use ng-if):
 - [ ] policiesCtrl.js
 - [ ] rolesCtrl.js
 - [ ] roleMappingCtrl.js
 - [ ] usersCtrl.js

* The issue on the Role-Mapping table has been fixed

> ### Bugs
> * [x]  `Security < Role Mapping`: "No Authorization Token provided" as a reponse when a new Role-Mapping is created. The table refuses to show the new data. It also fails when sometimes when a role mapping is removed.

* The API Settings has been finished. Only Splunk admins can add, remove and edit APIs, as logged user needs write permissions on the Splunk's KVstore, and all Splunk admins have this permission by default.

**Comment by AlexRuiz7** [comment]
- [ ] Review the edit and delete icons on the action column of the ruleset tables

**Comment by AlexRuiz7** [comment]
All remaining issues that might be found will be tracked on independent issues and PRs.
