### ISSUE TITLE
Splunk - Release 4.3.8 - Release Candidate 1 - Testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1366]
## Description

We need to test the app packages for the upcoming version of Wazuh 4.3.8.

## Tasks
- [x] Smoke test - Splunk 8.2.6
- [x] Smoke test - Splunk 8.1.10
- [x] Smoke test - Splunk 8.1.7
- [x] Smoke test - Splunk 8.1.4

**Comment by AlexRuiz7** [comment]
We performed with @mauceballos the manual test for the marked packages without problems.

_Originally posted by @Mayons95 in https://github.com/wazuh/wazuh-splunk/issues/1362#issuecomment-1246752848_
