### ISSUE TITLE
Splunk - Release 4.3.7 RC1 - Wazuh UI Manual Testing

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-splunk#1376]
## Description

This issue is created to track the effort for the manual testing for package 4.3.9

## Tasks

- [ ] Smoke test - Splunk 8.2.8 
- [ ] Smoke test - Splunk 8.2.7
- [ ] Smoke test - Splunk 8.2.6
- [ ] Smoke test - Splunk 8.1.10
- [ ] Smoke test - Splunk 8.1.7
- [ ] Smoke test - Splunk 8.1.4

**Comment by mauceballos** [comment]
Smoke test 
<details>
<summary>8.1.4</summary

![2022-10-06_10-54](https://user-images.githubusercontent.com/76791841/194332100-7342c2f3-ec68-4a78-92eb-f71cd056ea15.png)
![2022-10-06_10-53](https://user-images.githubusercontent.com/76791841/194332115-37c034ee-4762-400a-90ac-d6e8410f1799.png)

</details>

**Comment by Mayons95** [comment]
Evidence for smoke test Splunk 8.2.8 - 4.3.9
<details>
https://github.com/wazuh/wazuh-splunk/issues/1376

![image](https://user-images.githubusercontent.com/104914131/194338622-e099a4c9-514f-44e7-8008-05b5994f382e.png)

</details>

**Comment by Mayons95** [comment]
Evidence for smoke test Splunk 8.2.6 - 4.3.9

<details>

![image](https://user-images.githubusercontent.com/104914131/194343822-39e8518e-deb7-41ac-9db2-25fa2076691b.png)

</details>

**Comment by mauceballos** [comment]
Smoke test 
<details>
<summary>8.1.10</summary

![2022-10-06_12-17](https://user-images.githubusercontent.com/76791841/194352587-a6b1370b-eeb7-4fc2-bc9d-b9f5b0187091.png)
![2022-10-06_12-19](https://user-images.githubusercontent.com/76791841/194352623-aba73d1c-b08a-4a48-be9b-2f9df835de09.png)



</details>
