### ISSUE TITLE
Improve Wazuh integration with Splunk

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1387]
## Description

We are defining a plan to improve our app for Splunk. This plan will roughly be composed of the following action items:

- [ ] Integration with Wazuh Stack (Indexer & Dashboard)

As part of the Open Source community, we want to allow our users to easily integrate Wazuh with external services, Splunk among them.

This would allow the users to exploit their data using the service they see fit, while managing Wazuh using the [Wazuh Components](https://documentation.wazuh.com/current/getting-started/components/index.html).

- [ ] Support new Splunk SDK

Our app is currently compatible with a wide range of Splunk versions. As the time moves on, the ways to develop apps for Splunk also moves on, so, in order to take advantage of the latest improvements in this area, our app also needs to evolve. We have to study these new development tools and evaluate what would be the impact on our app if we use the latest Splunk SDK.

- [ ] Support Splunk Cloud

This is a recurrent request by the community. There is no doubt that the community is interested in using our app in Splunk Cloud. We are aware of that, so, we'll evaluate if it's feasible to adapt our app to be cloud-ready by using the latest SDK.
