### ISSUE TITLE
Support for Wazuh 4.4.1

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1392]
## Description

Wazuh 4.4.1 will be released shortly. Our app for Splunk needs to support this new version. From our side, no changes will be included, so we only need to bump the version.

### Pre-release
- [x] #1393
- [x] Generate the required tags.
- [x] Generate packages.
- [x] Test the packages, to verify they install, and the app works as expected.
- [x] [Optional] Run Regression Testing (#issue) - skipped
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-splunk/wiki/Compatibility).

### Supported versions

Same as on previous releases: listed on our [supported versions](https://github.com/wazuh/wazuh-splunk/blob/master/scripts/tag.py#L7-L13).
