### ISSUE TITLE
Support for Wazuh 4.3.11

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-splunk#1396]
## Description

Wazuh 4.3.11 will be released shortly. Our app for Splunk needs to support this new version. From our side, no changes will be included, so we only need to bump the version.

### Pre-release
- [x] #1397 (bump).
- [x] Generate the required tags.
- [x] Generate packages.
- [x] #1399
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-splunk/wiki/Compatibility).

### Supported versions

Same as on previous releases: listed on our [supported versions](https://github.com/wazuh/wazuh-splunk/blob/1f65f02764013021dc71a1a02c9a8d5c52e421a4/scripts/tag.py#L7-L14).
