### ISSUE TITLE
Support for Wazuh 4.4.3

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1405]
## Description

Wazuh 4.4.3 will be released shortly. Our app for Splunk needs to support this new version. From our side, only #1406 will be included.

### Pre-release
- [x] Add support for Wazuh 4.4.3 (bump).
- [x] Generate the required tags.
- [x] Generate packages.
- [x] #1408
- [x] Generate draft releases.
- [x] Notify the @wazuh/cicd and @wazuh/content teams that the release is good to go, from our side.

### Post-release
- [x] Make draft releases final and public.
- [x] Sync branches.
- [x] Update [Compatibility Matrix](https://github.com/wazuh/wazuh-splunk/wiki/Compatibility).

### Supported versions

Same as on previous releases: listed on our [supported versions](https://github.com/wazuh/wazuh-splunk/blob/master/scripts/tag.py#L7-L13).
