### ISSUE TITLE
Maintain production and numbered branches post release v4.4.5

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-splunk#1418]
| Related issue |
| --- |
| wazuh/wazuh#17867 |

The goal is to complete the following tasks, each task must have a PR associated with this issue. 

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, merge-4.4.5-into-4.4.

Also, all PRs corresponding to the same phase (merge-X-into-Y) must be merged at the same time.

### Wazuh-splunk -> @wazuh/frontend
- [x] Merge tag `v4.4.5` into `4.4` (fast-forward) on wazuh-splunk repository --> #1419 
- [x] Delete branch `4.4.5` --> #1419 
- [x] Merge branch `4.4` into `4.5.0` on wazuh-splunk repository --> #1420 
- [x] Merge branch `4.5.0` into `4.5.1` on wazuh-splunk repository --> #1421 
- [x] Merge branch `4.5.1` into `4.6.0` on wazuh-splunk repository --> #1422 
- [x] Merge branch `4.6.0` into `master` on wazuh-splunk repository --> #1423
