### ISSUE TITLE
Support new stage RC 1 for 4.5.0 in wazuh-splunk repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-splunk#1447]
## Description

This issue attempts to support a new stage RC 1 for 4.5.0 in the wazuh-splunk repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.0
- [x] Create tag v4.5.0-rc1 from branch 4.5.0 on wazuh-splunk repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-splunk/releases/tag/v4.5.0-rc1
