### ISSUE TITLE
Support new stage Alpha 1 for 4.6.0 in wazuh-splunk repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-splunk#1468]
## Description

This issue attempts to support a new stage Alpha 1 for 4.6.0 in the wazuh-splunk repository.

## Tasks

- [ ] Ensure changelog is updated for 4.6.0 (if applicable).
- [ ] Create tag v4.6.0-alpha1 from branch 4.6.0 on wazuh-splunk repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-splunk/releases/tag/v4.6.0-alpha1.
