### ISSUE TITLE
Support new Wazuh version 4.5.4 in wazuh-splunk repository

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-splunk#1492]
## Description

This issue attempts to support a new version 4.5.4 in the wazuh-dashboard-plugins repository.

## Tasks

- [x] Create numbered branch for version (4.5.4) using tag v4.5.3 on wazuh-dashboard-plugins repository.
- [x] Bump 4.5.4 branch to 4.5.4 version on wazuh-dashboard-plugins repository, including revision and changelog.
  - [x] https://github.com/wazuh/wazuh-splunk/pull/1491
