### ISSUE TITLE
Support new stage Alpha 1 for 4.5.4 in wazuh-splunk repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-splunk#1493]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.4 in the wazuh-splunk repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.4 (if applicable).
- [x] Bump revision for branch 4.5.4 on wazuh-splunk repository.
  - [x] https://github.com/wazuh/wazuh-splunk/pull/1494
- [x] Create tag v4.5.4-alpha1 from branch 4.5.4 on wazuh-splunk repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-splunk/releases/tag/v4.5.4-8.2-alpha1.
