### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#389]
|Wazuh| Splunk |
| --- | --- |
| 4.2.x| 8.1.4 / 8.2.2 |

The app must use the RBAC implemented by the API.

## Run_as
- [x] #1149
- [x] #1174

## Strategy to map Splunk users with Wazuh users
- [x] Search for the Splunk API to get the logged user, and the list of users from the front side and the backside.
- [x] #1154
- [x] #1155
- [x] #1156

## Services (resolvers) to implement permissions to the resources.
- [x] Check permissions for the user on the frontend.  https://github.com/wazuh/wazuh-splunk/issues/1147
- [x] We should use a centralized dictionary for the relation between the sections and permission that they need https://github.com/wazuh/wazuh-splunk/issues/1159
- [x] #1161
- [x] #1170
- [x] #1164
## Management (users, policies, role mapping, etc).
- [x] Create security section to manage users, policies, roles and role mapping. https://github.com/wazuh/wazuh-splunk/issues/1148
- [x] CRUD users https://github.com/wazuh/wazuh-splunk/issues/1150
- [x] CRUD roles https://github.com/wazuh/wazuh-splunk/issues/1151
- [x] CRUD policies https://github.com/wazuh/wazuh-splunk/issues/1152
- [x] CRUD role mapping https://github.com/wazuh/wazuh-splunk/issues/1153

**Comment by sortizowlh** [comment]
Analyzing the implementation of RBAC in Splunk.

Currently, this issue has been moved to stale status due to the priority of this issue.
