### ISSUE TITLE
Splunkbase checklist not passing

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#484]
Hi, the app should complete the following checks in order to pass the validations on Splunkbase:

- [x] `static/appIconAlt.png` should be 36x36 or less, but was detected as 36x38.
- [x] `static/appLogo.png` should be 160x40 or less, but was detected as 198x44.
- [x] The `meta.local` file should not exist.
- [x] Do not generate `metal.local` file in the app.
- [x] `default` stanza was found in `default/web.conf`. Please remove any `[default], [general], [global]` stanzas or properties outside of a stanza (treated as default/global) from conf files defined by Splunk.These stanzas/properties are not permitted because they modify global settings outside the context of the app.
- [x] `indexes.conf` file should not exist in the app context. Apps and add-ons should not create indexes. Indexes should only be defined by Splunk System Administrators to meet the data storage and retention needs of the installation. Consider using Tags or Source Types to identify data instead index location.
- [x] Copy the `README` to the app folder.

Cheers

**Comment by manuasir** [comment]
Related issue: https://github.com/wazuh/wazuh-splunk/issues/483
Researching about how to avoid the `web.conf` issue.
