### ISSUE TITLE
Support for Wazuh 4.x

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#949]
Make Splunk Wazuh APP compatible with Wazuh 4.x

- [x] Adapt for break changes to consume Wazuh API (compatible with RBAC)
- [x] Adapt for deprecated endpoints of Wazuh API
- [x] Adapt for breack changes with Wazuh Manager
- [x] Analisis for new minimal viable functionalities with Wazuh 4.x
